[build]
builder = "NIXPACKS"
buildCommand = "cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
healthcheckPath = "/api/auth/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 