name: Deploy Backend to Railway

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Tests
        run: |
          echo "Starting tests..."
          mvn test
          echo "Tests completed."
        
      - name: Build with Maven
        if: success()
        run: mvn -B package --file pom.xml