name: Deploy to Railway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Tests
        run: mvn -B test
        
      - name: Build with Maven
        if: success()
        run: mvn -B package --file pom.xml
        
      - name: Install Railway CLI
        if: success()
        run: npm install -g @railway/cli
        
      - name: Deploy to Railway
        if: success() && github.ref == 'refs/heads/main'
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY }} 