name: Deploy to Railway

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: |
          echo "Starting tests..."
          mvn test -B --fail-at-end surefire-report:report jacoco:report
          echo "Tests completed."

      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: |
            target/site/surefire-report.html
            target/site/jacoco/

      - name: Check Test Results
        run: |
          echo "Checking test results..."
          if [ -f target/surefire-reports/TEST-*.xml ]; then
            if grep -q "<failure" target/surefire-reports/TEST-*.xml || grep -q "<error" target/surefire-reports/TEST-*.xml; then
              echo "Tests failed!"
              exit 1
            else
              echo "All tests passed!"
            fi
          else
            echo "No test results found!"
            exit 1
          fi

      - name: Build with Maven
        if: success()
        run: |
          echo "Starting build..."
          mvn -B package --file pom.xml
          echo "Build completed."

      - name: Install Railway CLI
        if: success()
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        if: success() && github.ref == 'refs/heads/main'
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY }} 